FROM alpine:3
LABEL maintainer=jap1968
#ARG DEBIAN_FRONTEND=noninteractive
RUN apk update
RUN apk add composer
RUN apk add --no-cache \
    apache2 \
    php84-apache2 \
    php-mbstring \
    php-snmp \
    php-curl

RUN mkdir -p \
    /var/local/www/public/ \
    /var/local/www/src/ \
    /var/local/www/vendor/ \
    /var/local/www/logs/
# RUN chown www-data:www-data /var/local/www/logs/

COPY composer.json /var/local/www/
WORKDIR /var/local/www/
RUN composer install

COPY docker/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

COPY ./public/ /var/local/www/public/
COPY ./src/ /var/local/www/src/

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
